name: Deploy to Scaleway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Scaleway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SCALEWAY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SCALEWAY_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh ${{ secrets.SCALEWAY_USER }}@${{ secrets.SCALEWAY_HOST }} <<EOF
            set -e  # Stop script if any command fails

            echo "🚀 Déploiement en cours sur Scaleway..."

            # Aller dans le dossier du projet
            cd ~/questionnaire-app

            # Récupérer les dernières modifications du repo
            git reset --hard origin/main  # Supprime les changements locaux
            git pull origin main  # Récupère les dernières modifications

            # Arrêter l'ancienne version du backend & frontend sans supprimer les volumes
            sudo docker compose down

            # Nettoyage des images inutilisées pour éviter les conflits
            sudo docker system prune -af --volumes

            # Rebuild du projet sans supprimer les volumes MongoDB
            sudo docker compose build --no-cache

            # Démarrer les nouveaux services
            sudo docker compose up -d --build

            # Assurer que MongoDB et Nginx redémarrent bien
            sudo systemctl restart nginx

            echo "✅ Déploiement terminé avec succès !"
            exit
          EOF
