name: CI/CD Deployment to Scaleway

on:
  push:
    branches:
      - main

jobs:
  # Test d'intégration du backend (Jest + Supertest)
  test_backend:
    name: Run Backend Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache MongoDB binaries
        uses: actions/cache@v3
        with:
          path: ~/.cache/mongodb-binaries
          key: mongodb-binaries-v1

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Fix Jest Permissions
        run: chmod +x backend/node_modules/.bin/jest

      - name: Run Backend Integration Tests
        run: |
          cd backend
          export NODE_ENV=test 
          npm test -- --runInBand --forceExit --detectOpenHandles

  # Test unitaire du frontend (Vitest)
  test_frontend:
    name: Run Frontend Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run Frontend Unit Tests
        run: |
          cd frontend
          npm test

  # Déploiement sur Scaleway après tests réussis
  deploy:
    name: Deploy to Scaleway
    runs-on: ubuntu-latest
    needs: [test_backend, test_frontend]  # Déploiement uniquement si les tests réussissent

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SCALEWAY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SCALEWAY_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh ${{ secrets.SCALEWAY_USER }}@${{ secrets.SCALEWAY_HOST }} <<EOF
            set -e  # Arrêter le script en cas d'erreur
            cd ~/questionnaire-app
            git reset --hard origin/main  # Supprimer les changements locaux
            git pull origin main  # Récupérer les dernières modifications

            # Arrêter et nettoyer les anciens conteneurs
            sudo docker compose down
            sudo docker system prune -af  # Supprime tout le cache Docker

            # Rebuild total pour éviter les erreurs de cache
            sudo docker compose build --no-cache

            # Relancer les services
            sudo docker compose up -d
            sudo systemctl restart nginx  # Redémarrer Nginx
            exit
          EOF

