name: CI/CD Deployment to Scaleway

on:
  push:
    branches:
      - main

jobs:
  # Test Backend (Jest)
  test_backend:
    name: Run Backend Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd backend
          npm install
          npx jest --version  # Vérifie que Jest est bien installé

      - name: Fix Jest Permissions
        run: chmod +x backend/node_modules/.bin/jest  

      - name: Run unit tests (Jest)
        run: |
          cd backend
          npm test

  # Test Frontend (Vitest)
  test_frontend:
    name: Run Frontend Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd frontend
          npm install
          npx vitest --version  # Vérifie que Vitest est bien installé

      - name: Run unit tests (Vitest)
        run: |
          cd frontend
          npm run test

  # Déploiement sur Scaleway
  deploy:
    name: Deploy to Scaleway
    runs-on: ubuntu-latest
    needs: [test_backend, test_frontend]  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SCALEWAY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SCALEWAY_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh ${{ secrets.SCALEWAY_USER }}@${{ secrets.SCALEWAY_HOST }} <<EOF
            set -e  # Arrête le script en cas d'erreur
            cd ~/questionnaire-app
            git reset --hard origin/main  # Supprime les changements locaux
            git pull origin main  # Récupère les dernières modifications
            sudo docker compose down
            sudo docker system prune -af  # Nettoie les anciens conteneurs/images
            sudo docker compose build --no-cache frontend  # Rebuild complet du frontend
            sudo docker compose up -d --build
            sudo systemctl restart nginx  # Redémarre Nginx
            exit
          EOF
