name: Deploy to Scaleway

on:
  push:
    branches:
      - main

jobs:
  # 🚀 Test unitaire du frontend (Vitest)
  test_frontend:
    name: Run Frontend Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
          npx vitest --version  # Vérifie que Vitest est installé

      - name: Run Frontend Unit Tests
        run: |
          cd frontend
          npm run test

  # 🚀 Déploiement sur Scaleway (uniquement si les tests du frontend passent)
  deploy:
    runs-on: ubuntu-latest
    needs: [test_frontend]  # Bloque le déploiement si les tests échouent

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SCALEWAY_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SCALEWAY_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh ${{ secrets.SCALEWAY_USER }}@${{ secrets.SCALEWAY_HOST }} <<EOF
            cd ~/questionnaire-app
            git pull origin main
            sudo docker compose down
            sudo docker compose up -d --build
            sudo systemctl restart nginx
            exit
          EOF
